In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('House.csv')
df

Bedrooms  Bathrooms  Status  Location  Price  Facing  Type  Size
0           0          0       0        34     68       1     3  1944
1           2          2       1        17     45       1     0  1266
2           3          3       1        56     55       8     0  1587
3           0          0       2        31     15       0     3  1560
4           2          2       1        56     48       1     0  1450
..        ...        ...     ...       ...    ...     ...   ...   ...
955         0          0       2         4     85       8     3  2040
956         0          0       2         4     85       8     3  2040
957         0          0       2         4     85       8     3  2040
958         0          0       2         4     85       8     3  2040
959         0          0       0        80     19       0     3  2394

[960 rows x 8 columns]

In [3]:
df.head()

Bedrooms  Bathrooms  Status  Location  Price  Facing  Type  Size
0         0          0       0        34     68       1     3  1944
1         2          2       1        17     45       1     0  1266
2         3          3       1        56     55       8     0  1587
3         0          0       2        31     15       0     3  1560
4         2          2       1        56     48       1     0  1450

In [4]:
df.tail()

Bedrooms  Bathrooms  Status  Location  Price  Facing  Type  Size
955         0          0       2         4     85       8     3  2040
956         0          0       2         4     85       8     3  2040
957         0          0       2         4     85       8     3  2040
958         0          0       2         4     85       8     3  2040
959         0          0       0        80     19       0     3  2394

In [5]:
len(df)

960

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
a,b = np.arange(10).reshape(5,2),range(5)
a,b

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 range(0, 5))

In [8]:
p,q,r,s = train_test_split(a,b)
p,q,r,s

(array([[6, 7],
        [2, 3],
        [8, 9]]),
 array([[4, 5],
        [0, 1]]),
 [3, 1, 4],
 [2, 0])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Bedrooms   960 non-null    int64
 1   Bathrooms  960 non-null    int64
 2   Status     960 non-null    int64
 3   Location   960 non-null    int64
 4   Price      960 non-null    int64
 5   Facing     960 non-null    int64
 6   Type       960 non-null    int64
 7   Size       960 non-null    int64
dtypes: int64(8)
memory usage: 60.1 KB


In [10]:
x = df.drop(columns=['Price'])
y = df['Price']

In [11]:
x.head()

Bedrooms  Bathrooms  Status  Location  Facing  Type  Size
0         0          0       0        34       1     3  1944
1         2          2       1        17       1     0  1266
2         3          3       1        56       8     0  1587
3         0          0       2        31       0     3  1560
4         2          2       1        56       1     0  1450

In [12]:
y.head()

0    68
1    45
2    55
3    15
4    48
Name: Price, dtype: int64

In [13]:
x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [14]:
len(x_train),len(x_test)

(672, 288)

In [15]:
lin_reg = LinearRegression()

In [16]:
lin_reg.fit(x_train,y_train)

LinearRegression()

In [17]:
y_preds = lin_reg.predict(x_test)

In [18]:
y_test

836    71
477    22
350    46
893    35
923    38
       ..
501    56
796    29
634    37
405    18
741    25
Name: Price, Length: 288, dtype: int64

In [19]:
y_preds = lin_reg.predict(x_test)
y_preds

array([ 54.69996983,  28.08746257,  67.66160962,  47.24302235,
        47.36807514,  13.48458292,  28.08530399,  67.66160962,
        50.94386641,  25.97186358,  35.38425274,  47.37925222,
        16.71593079,  40.83750911,  29.6746125 ,  31.57778022,
        52.91384582,  28.65220981,  22.68018617,  68.88907429,
        90.65281912,  85.22359504,  38.14238033, 104.07887331,
        81.58589033,  26.70464787,  19.88499362,  29.36224391,
        35.97124914,  44.45958112,   5.23906504,  27.59796762,
        29.84106671,  57.40224485,  27.11243591,  51.79899914,
        27.01262138,  40.05810277,  47.98253396,  63.44785411,
        24.60583546,  35.27251858,  24.58088183,  21.97015207,
        20.06537538,   1.21833513,  11.98941893,  74.65984591,
        36.67213842,  13.30465172,  91.89411128,  21.18644249,
        31.458879  ,  31.32316904,  26.88612886,  25.5296998 ,
        63.53925666,  24.59616348,  52.29520299,  53.44000003,
        24.50431531,  13.27852094,  28.44279339,  65.19

In [20]:
from sklearn.metrics import r2_score,mean_squared_error

In [21]:
print("Linear Regression Metrics/Model Evaluation:")
print("R_Squared error:",r2_score(y_test,y_preds)) 

print('Mean Squared error:',mean_squared_error(y_test,y_preds))



Linear Regression Metrics/Model Evaluation:
R_Squared error: 0.5283378028443897
Mean Squared error: 276.44494751783685


In [ ]:
bedrooms = int(input('Enter no.of Bedrooms:'))
bathrooms =int( input('Enter no.of Bathrooms:'))
Status = int(input('Enter Status:'))
size = int(input('Enter SQFT:'))
location = int(input('Enter Location: '))
Facing = int(input('Enter Facing:'))
Type = int(input('Enter type:'))


Enter no.of Bedrooms: 556


In [ ]:
user_input = np.array([[bedrooms,bathrooms,Status,size,location,Facing,Type]])
user_input

In [ ]:
result = lin_reg.predict(user_input)[0]
result.round(2)

In [ ]:
import pickle
pickle.dump(lin_reg,open('lin_model.pkl','wb'))


In [ ]:
model = pickle.load(open('lin_model.pkl','rb'))

user_input = np.array([[bedrooms,bathrooms,Status,size,location,Facing,Type]])
#user_input
result = model.predict(user_input)[0]
result.round(2)


In [ ]:
!pip install Streamlit

In [ ]:
x.columns


